kind: pipeline
name: AppImage

steps:
- name: build
  image: nextcloudci/client-5.12:client-5.12-5
  commands:
    - /bin/bash -c "./admin/linux/build-appimage.sh"
    - /bin/bash -c "./admin/linux/upload-appimage.sh $DRONE_PULL_REQUEST $GIT_USERNAME $GIT_TOKEN"
  environment:
    GIT_USERNAME:
      from_secret: GIT_USERNAME
    GIT_TOKEN:
      from_secret: GIT_TOKEN
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
